export interface Contractor {
    companyName: string;
    city: string;
    province: string;
    postal_code: string;
    size: string;
    operations: string[];
    status: string;
    founded: string;
    capacity: string;
    address: string;
    phone: string;
    website: string;
    lat: number;
    lon: number;
}

export const contractorData: Contractor[] = [
    {
        companyName: "Marlo Logging Ltd",
        city: "Quesnel",
        province: "BC",
        postal_code: "V2J 3J2",
        size: "6-19 employed",
        operations: [],
        status: "Active",
        founded: "6/30/1989 0:00",
        capacity: "",
        address: "PO Box 4064 Stn Main",
        phone: "250-991-9904",
        website: "https://www.marlologging.ca/",
        lat: 53.0335006,
        lon: -122.4860933
    },
    {
        companyName: "Frost Lake Logging Ltd",
        city: "Prince George",
        province: "BC",
        postal_code: "",
        size: ">20 employees",
        operations: [],
        status: "",
        founded: "5/1/2019 0:00",
        capacity: "",
        address: "9653 Anzac Cres",
        phone: "250-562-2482",
        website: "https://www.frostlake.ca/",
        lat: 53.8361541,
        lon: -122.7348802
    },
    {
        companyName: "R. Clauson Logging Ltd.",
        city: "",
        province: "",
        postal_code: "",
        size: ">20 employees",
        operations: [],
        status: "",
        founded: "6/1/2011 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Hi-Sky Enterprises Ltd.",
        city: "",
        province: "",
        postal_code: "",
        size: ">20 employees",
        operations: [],
        status: "",
        founded: "12/3/1981 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Integrated Operations Group Inc.",
        city: "",
        province: "",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Shinedown Enterprises Ltd.",
        city: "",
        province: "",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "1/1/2019 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Tsi Del Del Enterprises Limited",
        city: "",
        province: "",
        postal_code: "",
        size: ">20 employees",
        operations: [],
        status: "",
        founded: "",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Volktrans-Canada Ltd.",
        city: "",
        province: "",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "3/6/2015 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "West Chilcotin Forest Products Ltd.",
        city: "",
        province: "",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "1/13/1994 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Timber Baron Contracting Ltd",
        city: "",
        province: "BC",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "9/1/2020 0:00",
        capacity: "",
        address: "4650 Lazelle Ave #203, Terrace",
        phone: "(250) 635-7677",
        website: "https://timberbaron.ca/",
        lat: 54.5178321,
        lon: -128.590911
    },
    {
        companyName: "Sarver Wood Fibre",
        city: "",
        province: "?",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "5/19/2005 0:00",
        capacity: "",
        address: "NA",
        phone: "(250) 395-1722",
        website: "https://sarverwood.com/",
        lat: 54.3264307,
        lon: -124.5268441
    },
    {
        companyName: "Amboy Logging Ltd",
        city: "",
        province: "BC",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "5/1/2016 0:00",
        capacity: "",
        address: "4238 Comeau Rd, Quesnel",
        phone: "(250) 992-8771",
        website: "NA",
        lat: 53.0330883,
        lon: -122.4853037
    },
    {
        companyName: "Suncoast Logging Ltd",
        city: "",
        province: "BC",
        postal_code: "",
        size: ">20 employees",
        operations: [],
        status: "",
        founded: "2/21/2006 0:00",
        capacity: "",
        address: "Gold Bridge",
        phone: "(250) 283-7764",
        website: "NA",
        lat: 50.855906,
        lon: -122.83414
    },
    {
        companyName: "Long's Logging",
        city: "Terrace",
        province: "BC",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "9/30/1999 0:00",
        capacity: "",
        address: "GD Lcd Main",
        phone: "250-615-2402",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Clusko Logging",
        city: "Kelowna",
        province: "BC",
        postal_code: "",
        size: ">20 employees",
        operations: ["Cut-to-length", "softwood for sawlogs and pulp", "incidental cut-to-length", "stump-to-dump delivery"],
        status: "",
        founded: "3/1/2018 0:00",
        capacity: "730,000 cubic metres",
        address: "153 Pinto Rd",
        phone: "250-765-3343",
        website: "",
        lat: 49.9190184,
        lon: -119.395615
    },
    {
        companyName: "Groot Bros Contracting Ltd",
        city: "",
        province: "",
        postal_code: "",
        size: "",
        operations: [],
        status: "",
        founded: "7/1/2011 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Freya Logging Inc",
        city: "",
        province: "",
        postal_code: "",
        size: "",
        operations: [],
        status: "",
        founded: "",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Nilsson Select Contracting Ltd.",
        city: "",
        province: "",
        postal_code: "",
        size: "2-5 employed",
        operations: [],
        status: "",
        founded: "3/15/2002 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Borland Creek Logging Ltd.",
        city: "",
        province: "",
        postal_code: "",
        size: ">20 employees",
        operations: [],
        status: "",
        founded: "7/7/1994 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "A.M. Anderson Ventures Ltd.",
        city: "",
        province: "",
        postal_code: "",
        size: "",
        operations: [],
        status: "",
        founded: "7/8/2015 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    },
    {
        companyName: "Skywest Environmental Inc.",
        city: "",
        province: "",
        postal_code: "",
        size: "6-19 employed",
        operations: [],
        status: "",
        founded: "1/21/2011 0:00",
        capacity: "",
        address: "",
        phone: "",
        website: "",
        lat: 0,
        lon: 0
    }
];