export interface Contractor {
    id: number;
    companyName: string;
    city: string;
    province: string;
    postal_code: string;
    size: string;
    operations: string[];
    status: string;
    founded: string;
    capacity: string;
    address: string;
    phone: string;
    website: string;
    lat: number;
    lon: number;
}

export const contractorData: Contractor[] = [
  {
    id: 1,
    companyName: "Marlo Logging Ltd",
    city: "Quesnel",
    province: "BC",
    postal_code: "V2J 3J2",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "6/30/1989 0:00",
    capacity: "",
    address: "PO Box 4064 Stn Main",
    phone: "250-991-9904",
    website: "https://www.marlologging.ca/",
    lat: 53.0335006,
    lon: -122.4860933
  },
  {
    id: 2,
    companyName: "Frost Lake Logging Ltd",
    city: "Prince George",
    province: "BC",
    postal_code: "V2N 0C6",
    size: ">20 employees",
    operations: [],
    status: "Active",
    founded: "5/1/2019 0:00",
    capacity: "",
    address: "9653 Anzac Cres",
    phone: "250-562-2482",
    website: "https://www.frostlake.ca/",
    lat: 53.8361541,
    lon: -122.7348802
  },
  {
    id: 3,
    companyName: "R. Clauson Logging Ltd.",
    city: "",
    province: "",
    postal_code: "",
    size: ">20 employees",
    operations: [],
    status: "Active",
    founded: "6/1/2011 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 4,
    companyName: "Hi-Sky Enterprises Ltd.",
    city: "",
    province: "",
    postal_code: "",
    size: ">20 employees",
    operations: [],
    status: "Active",
    founded: "12/3/1981 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 5,
    companyName: "Integrated Operations Group Inc.",
    city: "",
    province: "",
    postal_code: "",
    size: "6-19 employed",
    operations: [],
    status: "",
    founded: "",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 6,
    companyName: "Shinedown Enterprises Ltd.",
    city: "",
    province: "",
    postal_code: "",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "1/1/2019 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 7,
    companyName: "Tsi Del Del Enterprises Limited",
    city: "",
    province: "",
    postal_code: "",
    size: ">20 employees",
    operations: [],
    status: "",
    founded: "",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 8,
    companyName: "Volktrans-Canada Ltd.",
    city: "",
    province: "",
    postal_code: "",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "3/6/2015 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 9,
    companyName: "West Chilcotin Forest Products Ltd.",
    city: "",
    province: "",
    postal_code: "",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "1/13/1994 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 10,
    companyName: "Timber Baron Contracting Ltd",
    city: "",
    province: "BC",
    postal_code: "V8G 1S6",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "9/1/2020 0:00",
    capacity: "",
    address: "4650 Lazelle Ave #203, Terrace",
    phone: "(250) 635-7677",
    website: "https://timberbaron.ca/",
    lat: 54.5178321,
    lon: -128.590911
  },
  {
    id: 11,
    companyName: "Sarver Wood Fibre",
    city: "",
    province: "?",
    postal_code: "",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "5/19/2005 0:00",
    capacity: "",
    address: "NA",
    phone: "(250) 395-1722",
    website: "https://sarverwood.com/",
    lat: 54.3264307,
    lon: -124.5268441
  },
  {
    id: 12,
    companyName: "Amboy Logging Ltd",
    city: "",
    province: "BC",
    postal_code: "V2J 6W8",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "5/1/2016 0:00",
    capacity: "",
    address: "4238 Comeau Rd, Quesnel",
    phone: "(250) 992-8771",
    website: "NA",
    lat: 53.0330883,
    lon: -122.4853037
  },
  {
    id: 13,
    companyName: "Suncoast Logging Ltd",
    city: "",
    province: "BC",
    postal_code: "V0K 1P0",
    size: ">20 employees",
    operations: [],
    status: "Active",
    founded: "2/21/2006 0:00",
    capacity: "",
    address: "Gold Bridge",
    phone: "(250) 283-7764",
    website: "NA",
    lat: 50.855906,
    lon: -122.83414
  },
  {
    id: 14,
    companyName: "Long's Logging",
    city: "Terrace",
    province: "BC",
    postal_code: "V8G 4A1",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "9/30/1999 0:00",
    capacity: "",
    address: "GD Lcd Main",
    phone: "250-615-2402",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 15,
    companyName: "Clusko Logging",
    city: "Kelowna",
    province: "BC",
    postal_code: "V1V 2G9",
    size: ">20 employees",
    operations: ["Cut-to-length", "softwood for sawlogs and pulp", "incidental cut-to-length", "stump-to-dump delivery"],
    status: "Active",
    founded: "3/1/2018 0:00",
    capacity: "730,000 cubic metres",
    address: "153 Pinto Rd",
    phone: "250-765-3343",
    website: "",
    lat: 49.9190184,
    lon: -119.395615
  },
  {
    id: 16,
    companyName: "Groot Bros Contracting Ltd",
    city: "",
    province: "",
    postal_code: "",
    size: "",
    operations: [],
    status: "Active",
    founded: "7/1/2011 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 17,
    companyName: "Freya Logging Inc",
    city: "",
    province: "",
    postal_code: "",
    size: "",
    operations: [],
    status: "",
    founded: "",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 18,
    companyName: "Nilsson Select Contracting Ltd.",
    city: "",
    province: "",
    postal_code: "",
    size: "2-5 employed",
    operations: [],
    status: "Active",
    founded: "3/15/2002 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 19,
    companyName: "Borland Creek Logging Ltd.",
    city: "",
    province: "",
    postal_code: "",
    size: ">20 employees",
    operations: [],
    status: "Active",
    founded: "7/7/1994 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 20,
    companyName: "A.M. Anderson Ventures Ltd.",
    city: "",
    province: "",
    postal_code: "",
    size: "",
    operations: [],
    status: "Active",
    founded: "7/8/2015 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  },
  {
    id: 21,
    companyName: "Skywest Environmental Inc.",
    city: "",
    province: "",
    postal_code: "",
    size: "6-19 employed",
    operations: [],
    status: "Active",
    founded: "1/21/2011 0:00",
    capacity: "",
    address: "",
    phone: "",
    website: "",
    lat: 0,
    lon: 0
  }
]

export const sizes: string[] = [">20 employees", "6-19 employed", "2-5 employed", "Individual owner operator"];
export const statuses: string[] = ["Active", "Inactive"];
